/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.TelaDialogo.Classificação;
import view.TelaDialogo.Interpolaçao;
import view.TelaDialogo.ProdutoT;
import view.TelaDialogo.Razao;
import view.TelaDialogo.Razão2;
import view.TelaDialogo.Sn_FinitaA;
import view.TelaDialogo.Sn_FinitaB;
import view.TelaDialogo.Sn_Infinita;
import view.TelaDialogo.TermoCentral;
import view.TelaDialogo.TermoGeral;
import view.TelaDialogo.TermoGeral2;


/**
 *
 * @author maria
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PapelArea = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Menubotao = new javax.swing.JMenuBar();
        TermoG = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        SomaT = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        ProdutoT = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();

        setTitle("Qual Opção?");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagemllogo/Logo PGkkk.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("OBS: Para números decimais, utilize \".\" ao invés de \",\"");

        PapelArea.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PapelArea.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout PapelAreaLayout = new javax.swing.GroupLayout(PapelArea);
        PapelArea.setLayout(PapelAreaLayout);
        PapelAreaLayout.setHorizontalGroup(
            PapelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PapelAreaLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PapelAreaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(191, 191, 191))
        );
        PapelAreaLayout.setVerticalGroup(
            PapelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PapelAreaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        TermoG.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TermoG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icon/asterisk_orange.png"))); // NOI18N
        TermoG.setText("Termo Geral   ");
        TermoG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icon/calculator.png"))); // NOI18N
        jMenuItem1.setText("Calcular \"an\" em função de \"a1\"");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TermoGeral(evt);
            }
        });
        TermoG.add(jMenuItem1);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icon/calculator.png"))); // NOI18N
        jMenuItem11.setText("Calcular \"an\" em função de um \"termo qualquer\"");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TermoGeral2(evt);
            }
        });
        TermoG.add(jMenuItem11);

        Menubotao.add(TermoG);

        SomaT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SomaT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icon/asterisk_orange.png"))); // NOI18N
        SomaT.setText("Soma dos Termos   ");
        SomaT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icon/calculator.png"))); // NOI18N
        jMenuItem2.setText("Para P.G. Finita ->  Sn = an.q-a1/q-1 ");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SnFinitaA(evt);
            }
        });
        SomaT.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icon/calculator.png"))); // NOI18N
        jMenuItem3.setText("Para P.G. Finita ->  Sn = a1.((q ^ n) - 1)/q-1 ");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SnFinitaB(evt);
            }
        });
        SomaT.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icon/calculator.png"))); // NOI18N
        jMenuItem4.setText("Para P.G Infinita -> Sn = a1/ 1-q");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SnInfinita(evt);
            }
        });
        SomaT.add(jMenuItem4);

        Menubotao.add(SomaT);

        ProdutoT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ProdutoT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icon/asterisk_orange.png"))); // NOI18N
        ProdutoT.setText("Produto dos Termos   ");
        ProdutoT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icon/calculator.png"))); // NOI18N
        jMenuItem5.setText("Calcular \"pn\"");
        jMenuItem5.setBorder(null);
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutoDosTermos(evt);
            }
        });
        ProdutoT.add(jMenuItem5);

        Menubotao.add(ProdutoT);

        jMenu1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icon/asterisk_orange.png"))); // NOI18N
        jMenu1.setText("Classificação da P.G   ");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icon/text_padding_top.png"))); // NOI18N
        jMenuItem7.setText("Classificar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassificaçãoPG(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        Menubotao.add(jMenu1);

        jMenu2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icon/asterisk_orange.png"))); // NOI18N
        jMenu2.setText("Razão   ");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icon/calculator.png"))); // NOI18N
        jMenuItem9.setText("Calcular \"q\" em função de \"an\"");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RazãoA(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icon/calculator.png"))); // NOI18N
        jMenuItem8.setText("Calcular \"q\" sabendo 2 termos seguidos");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RazãoB(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        Menubotao.add(jMenu2);

        jMenu3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icon/asterisk_orange.png"))); // NOI18N
        jMenu3.setText("Termo Central   ");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icon/calculator.png"))); // NOI18N
        jMenuItem6.setText("Calcular \"TC\"");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TermoCentral(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        Menubotao.add(jMenu3);

        jMenu4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icon/asterisk_orange.png"))); // NOI18N
        jMenu4.setText(" Interpolação   ");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icon/calculator.png"))); // NOI18N
        jMenuItem10.setText("Interpolar");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Interpolação(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        Menubotao.add(jMenu4);

        setJMenuBar(Menubotao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PapelArea)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PapelArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TermoGeral(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TermoGeral
       setDefaultCloseOperation(TermoGeral.EXIT_ON_CLOSE);
       TermoGeral termo = new TermoGeral(this, true);
       termo.setLocationRelativeTo(null);
       termo.setVisible(true);
    }//GEN-LAST:event_TermoGeral

    private void ClassificaçãoPG(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassificaçãoPG
       Classificação classicarpg = new Classificação(this, true);
       classicarpg.setLocationRelativeTo(null);
       classicarpg.setVisible(true);
    }//GEN-LAST:event_ClassificaçãoPG

    private void SnFinitaA(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SnFinitaA
       Sn_FinitaA Sn = new Sn_FinitaA (this, true);
       Sn.setLocationRelativeTo(null);
       Sn.setVisible(true);

    }//GEN-LAST:event_SnFinitaA

    private void SnFinitaB(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SnFinitaB
       Sn_FinitaB Sn = new Sn_FinitaB (this, true);
       Sn.setLocationRelativeTo(null);
       Sn.setVisible(true);
        
    }//GEN-LAST:event_SnFinitaB

    private void SnInfinita(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SnInfinita
       Sn_Infinita sn = new Sn_Infinita (this, true);
       sn.setLocationRelativeTo(null);
       sn.setVisible(true);
    }//GEN-LAST:event_SnInfinita

    private void ProdutoDosTermos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutoDosTermos
       ProdutoT produto = new ProdutoT (this, true);
       produto.setLocationRelativeTo(null);
       produto.setVisible(true);
    }//GEN-LAST:event_ProdutoDosTermos

    private void RazãoA(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RazãoA
       Razao razao = new Razao (this, true);
       razao.setLocationRelativeTo(null);
       razao.setVisible(true);
    }//GEN-LAST:event_RazãoA

    private void RazãoB(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RazãoB
       Razão2 razao = new Razão2 (this, true);
       razao.setLocationRelativeTo(null);
       razao.setVisible(true);
    }//GEN-LAST:event_RazãoB

    private void TermoCentral(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TermoCentral
       TermoCentral TC = new TermoCentral (this, true);
       TC.setLocationRelativeTo(null);
       TC.setVisible(true);
    }//GEN-LAST:event_TermoCentral

    private void Interpolação(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Interpolação
       Interpolaçao interpolar = new Interpolaçao (this, true);
       interpolar.setLocationRelativeTo(null);
       interpolar.setVisible(true);
    }//GEN-LAST:event_Interpolação

    private void TermoGeral2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TermoGeral2
       setDefaultCloseOperation(TermoGeral.EXIT_ON_CLOSE);
       TermoGeral2 termo2 = new TermoGeral2(this, true);
       termo2.setLocationRelativeTo(null);
       termo2.setVisible(true);
    }//GEN-LAST:event_TermoGeral2

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menubotao;
    private javax.swing.JDesktopPane PapelArea;
    private javax.swing.JMenu ProdutoT;
    private javax.swing.JMenu SomaT;
    private javax.swing.JMenu TermoG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
